---
- name: Скопировать systemd unit-файл
  become: true
  template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service
    mode: '0644'

- name: Перезагрузить systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Включить и запустить сервис бэкенда
  become: true
  systemd:
    name: backend
    state: started
    enabled: yes