/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: martinjario (https://sketchfab.com/martinjario)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/skull-downloadable-1a9db900738d44298b0bc59f68123393
title: Skull downloadable
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";

export default function Skull() {
  const { nodes, materials } = useGLTF("/skull/skull.gltf");

  return (
    <mesh
      rotation={[-Math.PI / 2, 0, 0]}
      geometry={nodes.Object_2.geometry}
      material={materials.defaultMat}
    />
  );
}

useGLTF.preload("/skull/skull.gltf");
