---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  .dockerconfigjson: <dockerconfigjson>
type: kubernetes.io/dockerconfigjson
