---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  # Дефолтный тип сервиса - сервис доступен только внутри кластера
  type: ClusterIP
  ports:
    - protocol: TCP
      # Порт, на котором сервис будет доступен внутри кластера
      port: 8081
      # Порт, на который будет направляться трафик
      # в контейнере приложения.
      # В данном случае это порт, на котором запускается бэкенд
      targetPort: 8081
  # Селектор для выбора подов, к которым будет направляться трафик
  selector:
    app: backend
